name: 测试构建

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
         - platform: apollolake
           version: 7.0.1-42218
    steps:
      - name: 准备结束
        uses: actions/checkout@v2

      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: 配置引导镜像
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json
          sed -i -e 's\0x0001\0x5581\g' -e 's\0x46f4\0x0781\g' -e 's\1234XXX123\${{ secrets.DS918_JZ_SN }}\g' -e 's\XXYYXXYYXXYY\${{ secrets.DS918_JZ_MAC }}\g' ${{matrix.platform}}_user_config.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/igb/rpext-index.json          
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/e1000e/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbe/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/ixgbevf/rpext-index.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/vmxnet3/rpext-index.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json

      - name: 编译引导镜像
        run: ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}


      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-DS[39]*.img
          if-no-files-found: error


