name: 测试构建

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 编译 "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
         - platform: apollolake
           version: 7.0.1-42218
    steps:
      - name: 准备结束
        uses: actions/checkout@v2

      - name: 准备构建环境
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: 配置引导镜像
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json
          sed -i -e 's\0x0001\0x88AA\g' -e 's\0x46f4\0x88AA\g' -e 's\1234XXX123\0123456789\g' -e 's\XXYYXXYYXXYY\00AAAAAAAAAA\g' -e 's/00AAAAAAAAAA"/&,\n\t"mac2": "00BBBBBBBBBB",\n\t"mac2": "00CCCCCCCCCC",\n\t"netif_num": 3/' -e 's/"synoinfo": {},/"synoinfo": {\n\t"maxlanport": "3"\n    },/' ${{matrix.platform}}_user_config.json
          ./redpill_tool_chain.sh add https://raw.githubusercontent.com/pocopico/rp-ext/master/mpt2sas/rpext-index.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json

      - name: 编译引导镜像
        run: ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}


      - name: 上传引导镜像到 github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-DS[39]*.img
          if-no-files-found: error


