name: æ„å»º

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docker/**'
      - '**.sh'
      - '**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    name: ç¼–è¯‘ "${{matrix.platform}} ${{matrix.version}}"
    strategy:
      fail-fast: false
      matrix:
       include:
         - platform: ds3615xs
           version: 7.0.1-42218
    steps:
      - name: æ£€å‡ºé¡¹ç›®æ–‡ä»¶
        uses: actions/checkout@v2

      - name: ç¼“å­˜åŠ é€Ÿ
        uses: actions/cache@v2
        with:
          path: |
            cache/*.pat
            docker/downloads/*.txz
          key: ${{matrix.platform}}-${{matrix.version}}-${{ hashFiles('global_config.json') }}

      - name: å‡†å¤‡æ„å»ºç¯å¢ƒ
        run: |
          ./redpill_tool_chain.sh build ${{matrix.platform}}-${{matrix.version}}

      - name: é…ç½®å¼•å¯¼é•œåƒ
        run: |
          cp sample_user_config.json ${{matrix.platform}}_user_config.json

          # è°ƒæ•´VIDå’ŒPID
          sed -i -e 's/0x0001/0x88AA/g' -e 's/0x46f4/0x88AA/g' ${{matrix.platform}}_user_config.json

          # è°ƒæ•´SNå’ŒMAC æœ€å¥½ä½¿ç”¨ actions secrets å¼•å…¥
          sn=`./redpill_tool_chain.sh sn ${{matrix.platform}} | grep 'Serial Number' | awk '{print $3}'`
          sed -i -e "s/1234XXX123/${sn:="1130LWN123456"}/g" -e 's/XXYYXXYYXXYY/0011323D47F7/g' ${{matrix.platform}}_user_config.json

          # æ·»åŠ ç¬¬äºŒå¼ ç½‘å¡macå¹¶è®¾ç½®ç½‘å¡æ•°é‡
          sed -i -e 's/0011323D47F7"/&,\n\t"mac2": "0011323D47F8",\n\t"netif_num": 2/' ${{matrix.platform}}_user_config.json

          # è°ƒæ•´synoinfo
          sed -i -e 's/"synoinfo": {},/"synoinfo": {\n\t"maxlanport": "2"\n    },/' ${{matrix.platform}}_user_config.json

          cat ${{matrix.platform}}_user_config.json

      - name: æ·»åŠ æ‰©å±•é©±åŠ¨
        if: matrix.platform != 'dva3221'
        run: |
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-acpid/rpext-index.json
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-virtio/rpext-index.json

      - name: æ·»åŠ æ‰©å±•é©±åŠ¨[dva3221]
        if: matrix.platform == 'dva3221'
        run: |
          echo 'ç­‰å¾…æ•´ç†å…¼å®¹æ€§æ‰©å±•~ğŸ˜€'

      - name: æ·»åŠ  jumkey.misc
        if: endsWith(matrix.version,'42218') && matrix.platform != 'dva3221'
        run: |
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-misc/rpext-index.json

      - name: æ·»åŠ  jumkey.dtb !!!Create your own device tree binary!!!
        if: matrix.platform == 'ds920p' || matrix.platform == 'ds1621p'
        run: |
          ./redpill_tool_chain.sh add https://github.com/jumkey/redpill-load/raw/develop/redpill-dtb/rpext-index.json
          echo '!!!Create your own device tree binary!!!'
          echo 'see https://github.com/jumkey/redpill-load/blob/develop/redpill-dtb/README.md'

      - name: ç¼–è¯‘å¼•å¯¼é•œåƒ
        run: ./redpill_tool_chain.sh auto ${{matrix.platform}}-${{matrix.version}}


      - name: ä¸Šä¼ å¼•å¯¼é•œåƒåˆ° github actions
        uses: actions/upload-artifact@v2
        with:
          name: dsm-${{matrix.platform}}-${{matrix.version}}
          path: images/redpill-*.img
          if-no-files-found: error

      - name: åˆ é™¤æ—§çš„å·¥ä½œæµ
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 6

